export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-10 text-sm leading-6">
      <h1 className="text-2xl font-semibold mb-6">
        Privacy Policy
      </h1>

      <p className="mb-2 text-zinc-400">
        Last updated: April 28, 2026
      </p>
      <p className="mb-6 text-zinc-400">
        AICommunityLab is a free, non-commercial community platform. This
        notice describes how personal data is processed in connection with
        registration via Google and commenting on the site, in accordance with
        Regulation (EU) 2016/679 (GDPR), Hungarian Act CXII of 2011 on
        Informational Self-Determination and Freedom of Information (Infotv.)
        and Article VI(3) of the Fundamental Law of Hungary.
      </p>

      <h2 className="font-semibold mt-6 mb-2">1. Data Controller</h2>
      <p>
        Name: AICommunityLab (non-commercial community project)<br />
        Contact email: aicommunitylab@gmail.com<br />
        Website: https://aicommunitylab.com
      </p>
      <p className="mt-2 text-zinc-400">
        This project is operated by a private individual on a non-commercial
        basis and does not carry out commercial activity. No separate Data
        Protection Officer (DPO) has been appointed, as the processing does
        not meet the conditions of Article 37(1) GDPR.
      </p>

      <h2 className="font-semibold mt-6 mb-2">2. Categories of Personal Data Processed</h2>
      <p>Data received from Google (via OAuth, only the minimum scopes):</p>
      <ul className="list-disc ml-6">
        <li>Google account identifier (sub)</li>
        <li>Email address</li>
        <li>Display name</li>
        <li>Profile picture (avatar URL), if available</li>
      </ul>
      <p className="mt-2">Data generated by use of the service:</p>
      <ul className="list-disc ml-6">
        <li>Username, profile information you choose to provide</li>
        <li>Public comments and content you post on the platform</li>
        <li>Votes, reactions and similar interactions</li>
      </ul>
      <p className="mt-2">Technical data:</p>
      <ul className="list-disc ml-6">
        <li>IP address</li>
        <li>Browser and device information (user agent)</li>
        <li>Session and authentication tokens</li>
        <li>Server and security logs</li>
      </ul>

      <h2 className="font-semibold mt-6 mb-2">3. Purposes of Processing</h2>
      <ul className="list-disc ml-6">
        <li>Creating and operating user accounts</li>
        <li>Authenticating users via Google sign-in</li>
        <li>Enabling commenting and other community features</li>
        <li>Operating, maintaining and improving the website</li>
        <li>Ensuring security and preventing abuse and fraud</li>
        <li>Complying with legal obligations</li>
      </ul>
      <p className="mt-2 text-zinc-400">
        In line with the data minimisation principle (Article 5(1)(c) GDPR),
        only the data strictly necessary for these purposes is processed.
      </p>

      <h2 className="font-semibold mt-6 mb-2">4. Legal Basis</h2>
      <ul className="list-disc ml-6">
        <li>
          <strong>Article 6(1)(b) GDPR</strong> – performance of the user
          agreement: account creation, sign-in, publishing and storing
          comments, and providing the core community functionality.
        </li>
        <li>
          <strong>Article 6(1)(f) GDPR</strong> – legitimate interests:
          security, abuse and fraud prevention, integrity of the platform,
          and basic operational logging. The controller has weighed these
          interests against the rights and freedoms of the data subjects.
        </li>
        <li>
          <strong>Article 6(1)(c) GDPR</strong> – compliance with legal
          obligations, where applicable.
        </li>
      </ul>

      <h2 className="font-semibold mt-6 mb-2">5. Source of Data</h2>
      <p>
        Account data (such as name, email and profile picture) is received
        from Google through the OAuth sign-in flow that you initiate. The
        information made available to us depends on the permissions you grant
        in the Google consent screen (see Article 14 GDPR). All other data is
        collected directly from you when you use the service.
      </p>

      <h2 className="font-semibold mt-6 mb-2">6. Recipients and Data Processors</h2>
      <p>The following service providers may process personal data on our behalf:</p>
      <ul className="list-disc ml-6">
        <li>Supabase – authentication and database (EU region)</li>
        <li>Vercel – hosting and content delivery (EU region)</li>
        <li>Google LLC – OAuth identity provider</li>
      </ul>
      <p className="mt-2">
        Public comments and the associated public profile (display name and
        avatar) are visible to all visitors of the site by their nature.
      </p>

      <h2 className="font-semibold mt-6 mb-2">7. International Data Transfers</h2>
      <p>
        We aim to keep processing within the European Economic Area. Where a
        processor (such as Google) transfers data to a third country, the
        transfer is covered by the safeguards required under Chapter V GDPR
        (e.g. EU–US Data Privacy Framework or Standard Contractual Clauses).
      </p>

      <h2 className="font-semibold mt-6 mb-2">8. Data Retention</h2>
      <ul className="list-disc ml-6">
        <li>
          Account data: stored while the account is active, and deleted upon
          account deletion request or after a reasonable period of inactivity.
        </li>
        <li>
          Public comments and content: kept until you delete them or your
          account, or until removed by moderation. After account deletion the
          author attribution is anonymised.
        </li>
        <li>
          Technical and security logs: typically kept for up to 30 days,
          longer only if required for incident handling or by law.
        </li>
      </ul>

      <h2 className="font-semibold mt-6 mb-2">9. Data Subject Rights</h2>
      <p>Under Articles 15–22 GDPR you have the right to:</p>
      <ul className="list-disc ml-6">
        <li>Access your personal data</li>
        <li>Request rectification of inaccurate data</li>
        <li>Request erasure ("right to be forgotten")</li>
        <li>Restrict processing</li>
        <li>Object to processing based on legitimate interest</li>
        <li>Data portability, where applicable</li>
        <li>
          Withdraw consent at any time, where processing is based on consent
          (without affecting the lawfulness of processing carried out before
          withdrawal)
        </li>
      </ul>
      <p className="mt-2">
        To exercise these rights, contact us at aicommunitylab@gmail.com. We
        will respond within one month, in line with Article 12(3) GDPR.
      </p>

      <h2 className="font-semibold mt-6 mb-2">10. Right to Lodge a Complaint</h2>
      <p>
        You may lodge a complaint with the Hungarian National Authority for
        Data Protection and Freedom of Information (NAIH):
      </p>
      <ul className="list-disc ml-6">
        <li>Address: 1055 Budapest, Falk Miksa utca 9-11.</li>
        <li>Postal address: 1363 Budapest, Pf. 9.</li>
        <li>Email: ugyfelszolgalat@naih.hu</li>
        <li>Website: https://naih.hu</li>
      </ul>
      <p className="mt-2">
        You may also turn to a competent court for judicial remedy.
      </p>

      <h2 className="font-semibold mt-6 mb-2">11. Data Security</h2>
      <p>
        In line with Article 32 GDPR and Section 25/A of the Hungarian Infotv.,
        we apply technical and organisational measures appropriate to the risk,
        including HTTPS/TLS encryption in transit, access control, hardened
        authentication via Google OAuth, isolation of environments, and
        logging for incident handling. Only the minimum data necessary for the
        service is processed.
      </p>

      <h2 className="font-semibold mt-6 mb-2">12. Cookies and Similar Technologies</h2>
      <p>
        The service only uses cookies and similar storage that are strictly
        necessary for operation, such as session and authentication tokens
        and basic security tokens. No tracking, advertising or third-party
        analytics cookies are set without your consent.
      </p>

      <h2 className="font-semibold mt-6 mb-2">13. Automated Decision-Making</h2>
      <p>
        We do not carry out automated decision-making or profiling that
        produces legal effects on the data subject within the meaning of
        Article 22 GDPR.
      </p>

      <h2 className="font-semibold mt-6 mb-2">14. Mandatory or Voluntary Provision</h2>
      <p>
        Providing a Google account and the related basic profile data is
        necessary to use the registered features of the service. If you do
        not wish to provide this data, you cannot create an account or post
        comments, but you can still browse the publicly available pages.
      </p>

      <h2 className="font-semibold mt-6 mb-2">15. Changes to this Notice</h2>
      <p>
        This Privacy Policy may be updated to reflect changes in the service
        or in applicable law. The current version is always available on this
        page, with the date of the last update shown at the top.
      </p>
    </main>
  );
}
